### ISSUE TITLE
Cannot add random images to an array of UIImage

### ISSUE THREAD

**Issue by rl45** [carambalabs/UnsplashKit#13]
## What
>I want to add 10 random images to an array of UIImages

## Context
> My goal is to put the images into a table view

## Proposal
> Attach your own proposal *(if you have it)*. We'll discuss in on the issue to find the best one that fits into the library.

In addition, when I print the array count after adding it, it prints out 0. Why so?

Thank you.

<img width="854" alt="screen shot 2016-12-31 at 1 59 47 pm" src="https://cloud.githubusercontent.com/assets/18391736/21579392/9c387100-cf61-11e6-939d-8aa934c325e1.png">

**Comment by pepicrft** [comment]
@rl45 because by the point you print the count, images are being downloaded *(it's an asynchronous process)*
