### ISSUE TITLE
Unable to compile project

### ISSUE THREAD

**Issue by megimix** [carambalabs/UnsplashKit#14]
## What
 I get the following compile errors on file Source+Calls.swift
`Cannot convert value of type '(Result<UnsplashImage, NSError>) -> Void' to expected argument type '(Result<(UnsplashImage, URLResponse), NSError>) -> ()'`

## Context
I create new project [(https://github.com/megimix/UnsplashWeatherApp)] and install your pod.

**Comment by megimix** [comment]
I figure this out, the `CarambaKit` was updated to 1.0.7, and this pod didn't update with the new network layer.
A quick fix will be to add `pod "CarambaKit" , '1.0.6'` to podfile.
But the proper solution is to PR with updated version for the network layer.

**Comment by pepicrft** [comment]
Hey @megimix. I'm very sorry that it took us a lot of time to tackle this issue. I'm currently working on a solution for it. I'll keep you updated.

**Comment by pepicrft** [comment]
@megimix you should be able to compile the project now. Just update the version to `2.0.7`. Please, let me know if it works.
